"""`python -m qa dist` — build dist/ for npm and the CDN.

    dist/package.json          @quran-ws/assets
    dist/index.js .d.ts        the catalog as a typed module, with url()/get() helpers
    dist/catalog.json          copy of the root catalog, paths rewritten to the package
    dist/assets/...            the SVGs and their meta.json
    dist/sprites/<type>.svg    one <symbol> per style (colour variant) for a single request
    dist/fonts/AyahMarkers.*   the font-derived markers as a PUA font, + font-map.json
    dist/LICENSES.md           per-asset license status, generated from the catalog

The package stays `"private": true` while any bundled asset's license is not `confirmed`
(PLAN.md §6); npm refuses to publish it, which is the point — the legal decision is
Abdullah's, not the build's.
"""
import json
import re
import shutil
import xml.etree.ElementTree as ET

from qa import ROOT, git_rev
from qa.font import selection
from qa.font.fontbuild import main as fontbuild

DIST = ROOT / "dist"
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)
PACKAGE = "@quran-ws/assets"
VERSION = "0.1.0"


def _namespace_ids(svg_text, prefix):
    """Rewrite the internal ids of one asset so several can share a sprite sheet."""
    ids = set(re.findall(r'\sid="([^"]+)"', svg_text))
    for name in ids:
        svg_text = svg_text.replace(f'id="{name}"', f'id="{prefix}-{name}"')
        svg_text = svg_text.replace(f'href="#{name}"', f'href="#{prefix}-{name}"')
        svg_text = svg_text.replace(f'url(#{name})', f'url(#{prefix}-{name})')
    return svg_text


def sprite(assets, variant="color"):
    """One <symbol> per asset; <use href="#<type>-<style>"> renders it."""
    out = [f'<svg xmlns="{NS}" style="display:none" data-generated-by="qa dist {VERSION}">']
    for asset in assets:
        source = ROOT / asset["variants"][variant]
        body = source.read_text()
        inner = body.split(">", 1)[1].rsplit("</svg>", 1)[0]
        symbol_id = asset["id"].replace("/", "-")
        inner = _namespace_ids(inner, symbol_id)
        root_attrs = dict(re.findall(r'([a-zA-Z-]+)="([^"]*)"', body.split(">", 1)[0]))
        keep = {k: v for k, v in root_attrs.items() if k.startswith("data-") or k == "viewBox"}
        attrs = " ".join(f'{k}="{v}"' for k, v in keep.items())
        out.append(f'<symbol id="{symbol_id}" {attrs}>{inner}</symbol>')
    out.append("</svg>")
    return "\n".join(out)


def licenses_md(catalog):
    rows = ["# Licenses", "",
            "Generated by `python -m qa dist` from `catalog.json`. Each asset's full provenance "
            "(mushaf, archive.org item, PDF sha256, page, crop box) is in the catalog entry.", "",
            "| asset | lineage | license | status |", "|---|---|---|---|"]
    for asset in catalog["assets"]:
        licence = asset["license"]
        rows.append(f"| `{asset['id']}` | {asset['lineage']} | {licence['id']} | {licence['status']} |")
    notes = {a["license"].get("note") for a in catalog["assets"] if a["license"].get("note")}
    rows += ["", "## Notes", ""] + [f"* {note}" for note in sorted(notes)]
    rows += ["", "Attribution required by the assets above:", ""]
    rows += sorted({f"* {a['license']['attribution']}" for a in catalog["assets"] if a["license"].get("attribution")})
    return "\n".join(rows) + "\n" + source_licenses(catalog)


def source_licenses(catalog):
    """The source licences themselves, in full.

    The OFL requires that the licence and copyright notice travel with the material, so
    linking to them is not enough: a package containing OFL outlines has to carry the text.
    These are the same files `qa validate` accepts as evidence, so the package cannot claim
    a licence the repository has no record of.
    """
    wanted = sorted({re.sub(r"[^a-z0-9]+", "", source["family"].lower())
                     for asset in catalog["assets"] for source in asset["sources"] if source.get("family")})
    out = []
    for key in wanted:
        path = ROOT / "sources/licenses" / f"{key}.txt"
        if path.exists():
            out += ["", "---", "", f"## {key}", "", "```", path.read_text().rstrip(), "```"]
    if not out:
        return ""
    return "\n".join(["", "", "# Source licences", "",
                       "Reproduced in full because the OFL requires the licence and copyright notice "
                       "to travel with the material. Generated from `sources/licenses/`."] + out) + "\n"


INDEX_JS = '''// %(package)s — generated by `python -m qa dist`. Do not edit.
import catalog from "./catalog.json" with { type: "json" };

export const version = "%(version)s";
export const assets = catalog.assets;
export const byId = Object.fromEntries(assets.map((a) => [a.id, a]));

/** One asset, e.g. get("surah-headers", "mushaf-qalon"). */
export function get(type, style) {
  return byId[`${type}/${style}`];
}

/** Every asset of a type, in catalog order; optionally of one lineage.
 *  ofType("ayah-markers") is all 55; ofType("ayah-markers", "scan") is the 8 traced from
 *  mushaf scans, which are the ones that match a riwaya. */
export function ofType(type, lineage) {
  return assets.filter((a) => a.type === type && (!lineage || a.lineage === lineage));
}

/**
 * URL of one variant. `base` defaults to this module's own directory, so it works from a
 * CDN unchanged; pass a base to serve the files from your own origin.
 */
export function url(asset, variant = "color", base = new URL("./", import.meta.url)) {
  const entry = typeof asset === "string" ? byId[asset] : asset;
  if (!entry) throw new Error(`unknown asset: ${asset}`);
  const file = entry.variants[variant];
  if (!file) throw new Error(`${entry.id} has no ${variant} variant`);
  return new URL(file, base).href;
}

/** The slot an app draws into (surah name, ayah number, text area), in viewBox units. */
export function slot(asset, role) {
  const entry = typeof asset === "string" ? byId[asset] : asset;
  return role ? entry.slots.find((s) => s.role === role) : entry.slots[0];
}

/**
 * Draw a 9-sliced page frame at any page size, as an <svg> element.
 *
 * The corner motif keeps its shape at every size; only the edge units repeat, stretched by
 * the rounding remainder so the run fits exactly. Frames without slices (a border that does
 * not tile) have no `slices` entry — use their color.svg and scale it.
 *
 *   const svg = await frame(get("page-frames", "mushaf-qalon"), { width: 210, height: 297 });
 *   document.body.append(svg);
 *
 * `width`/`height` are the box you want in the returned viewBox's units; anything else
 * (mm, px, a CSS aspect box) is CSS's job. `fetchPiece` is injected for tests.
 */
export async function frame(asset, { width, height, base, fetchPiece } = {}) {
  const entry = typeof asset === "string" ? byId[asset] : asset;
  if (!entry?.slices) throw new Error(`${entry?.id ?? asset} has no slices`);
  const { corner, repeat, corner_mode, files } = entry.slices;
  const load = fetchPiece ?? (async (name) => {
    const response = await fetch(new URL(files[name], base ?? new URL("./", import.meta.url)).href);
    if (!response.ok) throw new Error(`cannot load ${files[name]}: ${response.status}`);
    return response.text();
  });
  const [cornerSvg, edgeH, edgeV] = await Promise.all([load("corner"), load("edge-h"), load("edge-v")]);
  const inner = (text) => {
    const body = text.slice(text.indexOf(">") + 1, text.lastIndexOf("</svg>"));
    const end = body.indexOf("</metadata>");
    return end === -1 ? body : body.slice(end + "</metadata>".length);
  };
  const rotate = corner_mode === "rotate";
  const parts = [];
  const place = (id, transform) => parts.push(`<use href="#${id}" transform="${transform}"/>`);
  place("qa-corner", "translate(0 0)");
  place("qa-corner", rotate ? `matrix(-1 0 0 -1 ${width} ${corner.h})` : `translate(${width} 0) scale(-1 1)`);
  place("qa-corner", rotate ? `matrix(-1 0 0 -1 ${corner.w} ${height})` : `translate(0 ${height}) scale(1 -1)`);
  place("qa-corner", rotate ? `translate(${width - corner.w} ${height - corner.h})` : `matrix(-1 0 0 -1 ${width} ${height})`);
  const run = (total, unit) => {
    const count = Math.max(1, Math.round(total / unit));
    return { count, step: total / count };
  };
  const across = run(width - 2 * corner.w, repeat.h);
  for (let i = 0; i < across.count; i++) {
    const x = corner.w + i * across.step, k = across.step / repeat.h;
    place("qa-edge-h", `translate(${x} 0) scale(${k} 1)`);
    place("qa-edge-h", `translate(${x} ${height}) scale(${k} -1)`);
  }
  const down = run(height - 2 * corner.h, repeat.v);
  for (let i = 0; i < down.count; i++) {
    const y = corner.h + i * down.step, k = down.step / repeat.v;
    place("qa-edge-v", `translate(0 ${y}) scale(1 ${k})`);
    place("qa-edge-v", `translate(${width} ${y}) scale(-1 ${k})`);
  }
  const markup = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" data-asset="page-frame" data-assembled-from="slices">` +
    `<defs><g id="qa-corner">${inner(cornerSvg)}</g><g id="qa-edge-h">${inner(edgeH)}</g><g id="qa-edge-v">${inner(edgeV)}</g></defs>` +
    parts.join("") + `</svg>`;
  return new DOMParser().parseFromString(markup, "image/svg+xml").documentElement;
}

export default { version, assets, byId, get, ofType, url, slot, frame };
'''

INDEX_DTS = '''// %(package)s — generated by `python -m qa dist`. Do not edit.
export type AssetType = "surah-headers" | "page-frames" | "ayah-markers";
export type Variant = "color" | "mono" | "line";
export type Lineage = "scan" | "font";
export type SlotRole = "surah-name" | "text-area" | "ayah-number";

/** Where the app draws, in viewBox units. `cx`/`cy` is the centre; `r` (font-derived
 *  markers) is the largest circle that fits the interior, for a round badge instead of a
 *  box. Size an ayah number by `h`, never by `w`: `w` is the three-digit case and is about
 *  2.7x too wide for one digit. */
export interface Slot { role: SlotRole; x: number; y: number; w: number; h: number; cx: number; cy: number; r?: number }

/** Font metrics of a font-derived asset, kept so the artwork can be taken back to UPEM
 *  units. `upem` is the source font's (1000, 2048 or 3000), not a constant. */
export interface FontMetrics { upem: number; advance: number; upem_scale: number; codepoint: string; glyph: string }
export interface Slices {
  files: { corner: string; "edge-h": string; "edge-v": string };
  corner: { w: number; h: number };
  repeat: { h: number; v: number };
  corner_mode: "mirror" | "rotate";
  reconstruction_iou: number;
}
export interface PaletteEntry { name: string; hex: string; stroke?: true }
export interface License { id: string; status: "confirmed" | "provisional" | "pending"; attribution?: string; note?: string }
export interface Source { kind: "mushaf-scan" | "font"; [key: string]: unknown }

export interface Asset {
  id: string;
  type: AssetType;
  style: string;
  lineage: Lineage;
  units: "normalized-100" | "font-upem";
  font?: FontMetrics;
  riwaya?: string | null;
  viewBox: string;
  aspect: number;
  variants: Partial<Record<Variant, string>>;
  source_crop?: string;
  palette: PaletteEntry[];
  stroke_widths_px?: number[] | null;
  slots: Slot[];
  symmetry?: 1 | 2 | 4 | "c2" | null;
  sources: Source[];
  slices?: Slices;
  license: License;
  pipeline_commit?: string | null;
}

export declare const version: string;
export declare const assets: Asset[];
export declare const byId: Record<string, Asset>;
export declare function get(type: AssetType, style: string): Asset | undefined;
export declare function ofType(type: AssetType, lineage?: Lineage): Asset[];
export declare function url(asset: Asset | string, variant?: Variant, base?: string | URL): string;
export declare function slot(asset: Asset | string, role?: SlotRole): Slot | undefined;
export declare function frame(
  asset: Asset | string,
  options: { width: number; height: number; base?: string | URL; fetchPiece?: (name: "corner" | "edge-h" | "edge-v") => Promise<string> }
): Promise<SVGSVGElement>;
declare const _default: { version: string; assets: Asset[]; byId: Record<string, Asset>; get: typeof get; ofType: typeof ofType; url: typeof url; slot: typeof slot; frame: typeof frame };
export default _default;
'''


def main(exclude_unconfirmed=False):
    catalog = json.loads((ROOT / "catalog.json").read_text())
    if exclude_unconfirmed:
        # Not the default. Every asset ships flagged, and `private: true` is what actually
        # stops a release; this is here so the call can be made at release time with a flag
        # rather than by editing the pipeline. See qa/licenses.json.
        kept = [a for a in catalog["assets"] if a["license"]["status"] == "confirmed"]
        dropped = len(catalog["assets"]) - len(kept)
        catalog = dict(catalog, assets=kept, count=len(kept))
        print(f"excluding {dropped} assets whose license is not confirmed")
    if DIST.exists():
        shutil.rmtree(DIST)
    (DIST / "sprites").mkdir(parents=True)

    for asset in catalog["assets"]:
        target = DIST / "assets" / asset["type"] / asset["style"]
        target.mkdir(parents=True, exist_ok=True)
        for relative in list(asset["variants"].values()):
            shutil.copy2(ROOT / relative, target / relative.rsplit("/", 1)[1])
        for relative in (asset.get("slices") or {}).get("files", {}).values():
            (target / "slices").mkdir(exist_ok=True)
            shutil.copy2(ROOT / relative, target / "slices" / relative.rsplit("/", 1)[1])
        shutil.copy2(ROOT / "assets" / asset["type"] / asset["style"] / "meta.json", target / "meta.json")

    for asset_type in sorted({a["type"] for a in catalog["assets"]}):
        of_type = [a for a in catalog["assets"] if a["type"] == asset_type]
        (DIST / "sprites" / f"{asset_type}.svg").write_text(sprite(of_type))

    font_markers = [m for m in selection() if f"ayah-markers/font-{m['id']}" in {a["id"] for a in catalog["assets"]}]
    if font_markers:
        fontbuild(DIST / "fonts", font_markers)

    (DIST / "catalog.json").write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n")
    (DIST / "index.js").write_text(INDEX_JS % {"package": PACKAGE, "version": VERSION})
    (DIST / "index.d.ts").write_text(INDEX_DTS % {"package": PACKAGE})
    (DIST / "LICENSES.md").write_text(licenses_md(catalog))
    shutil.copy2(ROOT / "LICENSE.md", DIST / "LICENSE.md")

    unconfirmed = [a["id"] for a in catalog["assets"] if a["license"]["status"] != "confirmed"]
    package = {
        "name": PACKAGE,
        "version": VERSION,
        "description": "Decorative Quran assets: surah headers, page frames and ayah markers as standardized, recolourable SVGs.",
        "type": "module",
        "main": "index.js",
        "module": "index.js",
        "types": "index.d.ts",
        "exports": {
            ".": {"types": "./index.d.ts", "import": "./index.js"},
            "./catalog.json": "./catalog.json",
            "./assets/*": "./assets/*",
            "./sprites/*": "./sprites/*",
            "./fonts/*": "./fonts/*",
        },
        "files": ["index.js", "index.d.ts", "catalog.json", "assets", "sprites", "fonts", "LICENSE.md", "LICENSES.md"],
        "sideEffects": False,
        "license": "SEE LICENSE IN LICENSES.md",
        "homepage": "https://assets.quran.ws",
        "repository": {"type": "git", "url": "git+https://github.com/quran-ws/quran-assets.git"},
        "private": bool(unconfirmed),
        "quranAssets": {"pipeline": git_rev(), "assets": catalog["count"],
                        "fontGlyphs": len(font_markers), "unconfirmedLicenses": unconfirmed},
    }
    (DIST / "package.json").write_text(json.dumps(package, indent=2) + "\n")

    size = sum(p.stat().st_size for p in DIST.rglob("*") if p.is_file())
    print(f"dist/: {catalog['count']} assets, {size/1e6:.1f} MB")
    if unconfirmed:
        print(f'dist/package.json is "private": true — {len(unconfirmed)} assets are not license-confirmed; npm will refuse to publish it.')


if __name__ == "__main__":
    main()
